/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCorporationsCorporationIdMedalsIssued200Ok {
    /**
     * ID of the character who was rewarded this medal
     */
    characterId: number;
    /**
     * issued_at string
     */
    issuedAt: Date;
    /**
     * ID of the character who issued the medal
     */
    issuerId: number;
    /**
     * medal_id integer
     */
    medalId: number;
    /**
     * reason string
     */
    reason: string;
    /**
     * status string
     */
    status: GetCorporationsCorporationIdMedalsIssued200Ok.StatusEnum;
}
export namespace GetCorporationsCorporationIdMedalsIssued200Ok {
    export type StatusEnum = 'private' | 'public';
    export const StatusEnum = {
        Private: 'private' as StatusEnum,
        Public: 'public' as StatusEnum
    }
}
