/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * wallet transaction
 */
export interface GetCorporationsCorporationIdWalletsDivisionTransactions200Ok {
    /**
     * client_id integer
     */
    clientId: number;
    /**
     * Date and time of transaction
     */
    date: Date;
    /**
     * is_buy boolean
     */
    isBuy: boolean;
    /**
     * -1 if there is no corresponding wallet journal entry
     */
    journalRefId: number;
    /**
     * location_id integer
     */
    locationId: number;
    /**
     * quantity integer
     */
    quantity: number;
    /**
     * Unique transaction ID
     */
    transactionId: number;
    /**
     * type_id integer
     */
    typeId: number;
    /**
     * Amount paid per unit
     */
    unitPrice: number;
}
