/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 200 ok object
 */
export interface GetCorporationsCorporationIdCustomsOffices200Ok {
    /**
     * Only present if alliance access is allowed
     */
    allianceTaxRate?: number;
    /**
     * standing_level and any standing related tax rate only present when this is true
     */
    allowAccessWithStandings: boolean;
    /**
     * allow_alliance_access boolean
     */
    allowAllianceAccess: boolean;
    /**
     * bad_standing_tax_rate number
     */
    badStandingTaxRate?: number;
    /**
     * corporation_tax_rate number
     */
    corporationTaxRate?: number;
    /**
     * Tax rate for entities with excellent level of standing, only present if this level is allowed, same for all other standing related tax rates
     */
    excellentStandingTaxRate?: number;
    /**
     * good_standing_tax_rate number
     */
    goodStandingTaxRate?: number;
    /**
     * neutral_standing_tax_rate number
     */
    neutralStandingTaxRate?: number;
    /**
     * unique ID of this customs office
     */
    officeId: number;
    /**
     * reinforce_exit_end integer
     */
    reinforceExitEnd: number;
    /**
     * Together with reinforce_exit_end, marks a 2-hour period where this customs office could exit reinforcement mode during the day after initial attack
     */
    reinforceExitStart: number;
    /**
     * Access is allowed only for entities with this level of standing or better
     */
    standingLevel?: GetCorporationsCorporationIdCustomsOffices200Ok.StandingLevelEnum;
    /**
     * ID of the solar system this customs office is located in
     */
    systemId: number;
    /**
     * terrible_standing_tax_rate number
     */
    terribleStandingTaxRate?: number;
}
export namespace GetCorporationsCorporationIdCustomsOffices200Ok {
    export type StandingLevelEnum = 'bad' | 'excellent' | 'good' | 'neutral' | 'terrible';
    export const StandingLevelEnum = {
        Bad: 'bad' as StandingLevelEnum,
        Excellent: 'excellent' as StandingLevelEnum,
        Good: 'good' as StandingLevelEnum,
        Neutral: 'neutral' as StandingLevelEnum,
        Terrible: 'terrible' as StandingLevelEnum
    }
}
