/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute } from './getDogmaDynamicItemsTypeIdItemIdDogmaAttribute';
import { GetDogmaDynamicItemsTypeIdItemIdDogmaEffect } from './getDogmaDynamicItemsTypeIdItemIdDogmaEffect';


/**
 * 200 ok object
 */
export interface GetDogmaDynamicItemsTypeIdItemIdOk {
    /**
     * The ID of the character who created the item
     */
    createdBy: number;
    /**
     * dogma_attributes array
     */
    dogmaAttributes: Array<GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute>;
    /**
     * dogma_effects array
     */
    dogmaEffects: Array<GetDogmaDynamicItemsTypeIdItemIdDogmaEffect>;
    /**
     * The type ID of the mutator used to generate the dynamic item.
     */
    mutatorTypeId: number;
    /**
     * The type ID of the source item the mutator was applied to create the dynamic item.
     */
    sourceTypeId: number;
}
