/**
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GetFwLeaderboardsCharactersActiveTotalActiveTotal } from './getFwLeaderboardsCharactersActiveTotalActiveTotal';
import { GetFwLeaderboardsCharactersLastWeekLastWeek } from './getFwLeaderboardsCharactersLastWeekLastWeek';
import { GetFwLeaderboardsCharactersYesterdayYesterday } from './getFwLeaderboardsCharactersYesterdayYesterday';


/**
 * Top 100 rankings of pilots by number of kills from yesterday, last week and in total.
 */
export interface GetFwLeaderboardsCharactersKills {
    /**
     * Top 100 ranking of pilots active in faction warfare by total kills. A pilot is considered \"active\" if they have participated in faction warfare in the past 14 days.
     */
    activeTotal: Array<GetFwLeaderboardsCharactersActiveTotalActiveTotal>;
    /**
     * Top 100 ranking of pilots by kills in the past week
     */
    lastWeek: Array<GetFwLeaderboardsCharactersLastWeekLastWeek>;
    /**
     * Top 100 ranking of pilots by kills in the past day
     */
    yesterday: Array<GetFwLeaderboardsCharactersYesterdayYesterday>;
}
